services:
  web:
    build: ./app
    container_name: dlp_web
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
     - ./app/.env
    depends_on:
      - db
      - rabbitmq

  db:
    image: mysql:9.1.0
    container_name: dlp_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: dlp_project
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  rabbitmq:
    image: "rabbitmq:4.0.2-management"
    container_name: dlp_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  dlp_manager:
    build: ./dlp_container
    container_name: dlp_manager
    command: python run.py
    env_file:
      - ./dlp_container/.env
    depends_on:
      - rabbitmq

volumes:
  db_data:
