services:
  web:
    build: ./app
    container_name: dlp_web
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - DJANGO_DEBUG=1
      - DJANGO_SECRET_KEY=your_secret_key
      - DJANGO_ALLOWED_HOSTS=localhost
      - MYSQL_DATABASE=dlp_project
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - db
      - rabbitmq

  db:
    image: mysql:9.1.0
    container_name: dlp_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: dlp_project
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  rabbitmq:
    image: "rabbitmq:4.0.2-management"
    container_name: dlp_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  db_data:
