# Generated by Django 5.1.2 on 2024-10-26 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pattern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "regex",
                    models.TextField(
                        help_text="Regular expression pattern to detect sensitive data"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the pattern", null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScannedMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="The content of the message or file scanned"
                    ),
                ),
                (
                    "detected",
                    models.BooleanField(
                        default=False, help_text="Whether sensitive data was detected"
                    ),
                ),
                ("scanned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "matched_pattern",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="dlp.pattern",
                    ),
                ),
            ],
        ),
    ]
